#include "Writer.h"
#include <iostream>
#include <fstream>
#include <iomanip>

static bool isNumericType(const ColDef& col) {
    return col.type == ColType::INT || col.type == ColType::BOOL;
}

void printConsole(const Schema& schema, const std::vector<Row>& rows) {
    constexpr int W = 18;
    std::cout << '\n';
    for (const auto& col : schema.columns)
        std::cout << std::left << std::setw(W) << col.name.substr(0, W - 1);
    std::cout << '\n' << std::string(W * schema.columns.size(), '-') << '\n';

    for (const auto& row : rows) {
        for (size_t i = 0; i < row.size(); ++i)
            std::cout << std::left << std::setw(W) << row[i].substr(0, W - 1);
        std::cout << '\n';
    }
    std::cout << '\n';
}

void writeCsv(const Schema& schema, const std::vector<Row>& rows, const std::string& path) {
    std::ofstream f(path);
    if (!f) { std::cerr << "[ERROR] Cannot write CSV: " << path << '\n'; return; }

    for (size_t i = 0; i < schema.columns.size(); ++i) {
        if (i) f << ',';
        f << schema.columns[i].name;
    }
    f << '\n';

    for (const auto& row : rows) {
        for (size_t i = 0; i < row.size(); ++i) {
            if (i) f << ',';
            f << '"' << row[i] << '"';
        }
        f << '\n';
    }
    std::cout << "[OK] CSV  -> " << path << '\n';
}

void writeSql(const Schema& schema, const std::vector<Row>& rows, const std::string& path) {
    std::ofstream f(path);
    if (!f) { std::cerr << "[ERROR] Cannot write SQL: " << path << '\n'; return; }

    f << "-- Generated by DummyDataGenerator\n"
      << "-- Table: " << schema.table << "  Rows: " << rows.size() << "\n\n";

    std::string cols;
    for (size_t i = 0; i < schema.columns.size(); ++i) {
        if (i) cols += ", ";
        cols += schema.columns[i].name;
    }

    for (const auto& row : rows) {
        f << "INSERT INTO " << schema.table << " (" << cols << ") VALUES (";
        for (size_t i = 0; i < row.size(); ++i) {
            if (i) f << ", ";
            if (isNumericType(schema.columns[i]))
                f << row[i];
            else
                f << '\'' << row[i] << '\'';
        }
        f << ");\n";
    }
    std::cout << "[OK] SQL  -> " << path << '\n';
}
